import { FsNode } from '~types/fs';

export const portfolioFs: FsNode = {
    type: 'dir',
    name: '~',
    children: [
        {
            type: 'file',
            name: 'README.md',
            content: [
                '# Afiq Akmal — afiqakm',
                '',
                'lead frontend / full-stack engineer · kuala lumpur · gmt+8',
                'web: afiqakm.dev',
                '',
                'motto: good UX is noticeable. great UX is imperceptible.',
                '',
                'you can browse this portfolio with unix commands.',
                'try:  ls   ·   cd work   ·   cat about.md   ·   help',
                '',
                'files of interest:',
                '  about.md      — the longer story',
                '  contact.md    — how to reach me',
                '  links.txt     — github and socials',
                '',
                'directories:',
                '  work/         — selected projects (cd work && ls)',
                '  writing/      — recent essays',
                '  stack/        — what i reach for',
            ].join('\n'),
        },
        {
            type: 'file',
            name: 'about.md',
            content: [
                '# about',
                '',
                "i'm Afiq Akmal, a Frontend Engineer based in Kuala Lumpur.",
                '3 years and counting. i build product surfaces — usually as the',
                'bridge between design, motion, and data at small teams.',
                '',
                'I like to think that I have a sense for how things should feel,',
                'and the technical chops to achive that feeling.',
                'I care deeply about micro-interactions,',
                'and the way a well-timed easing can make a list feel alive,',
                'without looking animated.',
                '',
                'three words my friends use: cheerful, flexible, loyal.',
                '',
                "the work i'm proudest of is the work nobody notices —",
                'a 200ms response that should have been 1.2s,',
                'a janky animation that should have been smooth,',
                'a frustrating edge case that should have been handled.',
                '',
            ].join('\n'),
        },
        {
            type: 'file',
            name: 'contact.md',
            content: [
                '# contact',
                '',
                'web       afiqakm.dev',
                'email     afiq98akmal@gmail.com',
                'github    github.com/afiqakm',
                'linkedin  linkedin.com/in/afiqakm',
                '',
                // 'open to: lead frontend / staff roles at small product teams,',
                // '         interesting freelance, late-stage thoughtful chats.',
                // '',
                // 'closed to: web3, "ai-first" anything, recruiter dms with',
                // '           "hi {{first_name}}" still in the template.',
            ].join('\n'),
        },
        {
            type: 'file',
            name: 'links.txt',
            content: [
                'afiqakm.dev',
                'github.com/afiqakm',
                'linkedin.com/in/afiqakm',
            ].join('\n'),
        },
        {
            type: 'dir',
            name: 'work',
            children: [
                {
                    type: 'file',
                    name: 'readme.md',
                    content: 'Work in progress or under NDA . heh .',
                },
            ],
        },
        // {
        //     type: 'dir',
        //     name: 'writing',
        //     children: [
        //         {
        //             type: 'file',
        //             name: '2026-05_friction.md',
        //             content: [
        //                 '# the opposite of friction is not speed',
        //                 '',
        //                 'may 2026 · 4 min read',
        //                 '',
        //                 'we keep optimizing for "fast." but most of the things',
        //                 'i remember loving — a film, a record, a meal — were not',
        //                 'fast. they were calm. friction is a distraction from',
        //                 'a poorly-defined goal; speed is what you get when you',
        //                 'remove the friction. but the goal was never speed.',
        //                 '',
        //                 '...continued at afiqakm.dev/friction',
        //             ].join('\n'),
        //         },
        //         {
        //             type: 'file',
        //             name: '2026-02_boring-tech.md',
        //             content: [
        //                 '# on choosing boring technology, again',
        //                 '',
        //                 'feb 2026 · 6 min read',
        //                 '',
        //                 "a senior engineer's case for being delightfully",
        //                 'uninteresting. the technologies you pick determine',
        //                 'the conversations you can have. boring tech buys you',
        //                 'attention you can spend somewhere that matters.',
        //                 '',
        //                 '...continued at afiqakm.dev/boring-tech',
        //             ].join('\n'),
        //         },
        //         {
        //             type: 'file',
        //             name: '2025-11_crdts.md',
        //             content: [
        //                 '# crdts for people who hate crdts',
        //                 '',
        //                 'nov 2025 · 11 min read',
        //                 '',
        //                 'a practical, mostly-correct guide. with pictures.',
        //                 'covers: why your collaborative editor probably does',
        //                 'not need yjs, why mine did, and how to tell which',
        //                 'side of that line you are on.',
        //             ].join('\n'),
        //         },
        //         {
        //             type: 'file',
        //             name: '2025-08_team-of-one.md',
        //             content: [
        //                 '# a team of one',
        //                 '',
        //                 'aug 2025 · 3 min read',
        //                 '',
        //                 'how leading frontend at a five-person company taught',
        //                 'me to delete things. mostly: my own code.',
        //             ].join('\n'),
        //         },
        //         {
        //             type: 'file',
        //             name: '2025-05_imperceptible.md',
        //             content: [
        //                 '# imperceptible animation',
        //                 '',
        //                 'may 2025 · 8 min read',
        //                 '',
        //                 'a piece on micro-motion: the 80ms easing that makes a',
        //                 'list feel "alive" without ever looking animated.',
        //             ].join('\n'),
        //         },
        //     ],
        // },
        {
            type: 'dir',
            name: 'stack',
            children: [
                {
                    type: 'file',
                    name: 'daily.toml',
                    content: [
                        '# things i write every day',
                        'languages   = ["typescript"]',
                        'frameworks  = ["react", "vite", "nextjs"]',
                        'styling     = ["tailwind", "css modules","sass"]',
                        'data        = ["axios", "react-query"]',
                    ].join('\n'),
                },
                // {
                //     type: 'file',
                //     name: 'often.toml',
                //     content: [
                //         '# things i pick up most weeks',
                //         'graphics    = ["three.js", "glsl", "canvas2d"]',
                //         'systems     = ["rust", "bun"]',
                //         'state       = ["zustand", "yjs"]',
                //         'testing     = ["playwright", "vitest"]',
                //     ].join('\n'),
                // },
                // {
                //     type: 'file',
                //     name: 'sometimes.toml',
                //     content: [
                //         '# tools i pull out for the right job',
                //         'native      = ["swift", "react native"]',
                //         'backend     = ["go", "elixir"]',
                //         'creative    = ["figma plugins", "webaudio"]',
                //     ].join('\n'),
                // },
                // {
                //     type: 'file',
                //     name: 'curious.toml',
                //     content: [
                //         "# things i'm studying in 2026",
                //         'effect_ts       = "structured concurrency in TS"',
                //         'mojo            = "python-shaped, MLIR-backed"',
                //         'wgpu            = "the shape of graphics post-webgpu"',
                //         'local_first     = "sync that is also offline-first"',
                //     ].join('\n'),
                // },
            ],
        },
        // {
        //     type: 'dir',
        //     name: 'now',
        //     children: [
        //         {
        //             type: 'file',
        //             name: 'now.md',
        //             content: [
        //                 '# now — may 2026',
        //                 '',
        //                 '· leading frontend on an unannounced collaborative tool',
        //                 '· writing every other friday at afiqakm.dev',
        //                 '· reading: "the timeless way of building" (alexander)',
        //                 '· running 35km/week, slowly',
        //                 '· learning: rust async, slowly',
        //                 '· not learning: web3, ever',
        //             ].join('\n'),
        //         },
        //     ],
        // },
    ],
};
