import { FsNode } from '~types/fs';

export const portfolioFs: FsNode = {
    type: 'dir',
    name: '~',
    children: [
        {
            type: 'file',
            name: 'README.md',
            content: [
                '# Afiq Akmal — afiqakm',
                '',
                'lead frontend / full-stack engineer · kuala lumpur · gmt+8',
                'web: afiqakm.dev',
                '',
                'motto: good UX is noticeable. great UX is imperceptible.',
                '',
                'you can browse this portfolio with unix commands.',
                'try:  ls   ·   cd work   ·   cat about.md   ·   help',
                '',
                'files of interest:',
                '  about.md      — the longer story',
                '  contact.md    — how to reach me',
                '  links.txt     — github / read.cv / are.na',
                '',
                'directories:',
                '  work/         — selected projects (cd work && ls)',
                '  writing/      — recent essays',
                '  stack/        — what i reach for',
                "  now/          — what i'm up to in may 2026",
            ].join('\n'),
        },
        {
            type: 'file',
            name: 'about.md',
            content: [
                '# about',
                '',
                "i'm Afiq Akmal (afiqakm) — a lead frontend / full-stack engineer.",
                'ten years in. i build product surfaces — usually as the',
                'bridge between design, motion, and data at small teams.',
                '',
                'i started writing javascript in 2014 because i wanted to',
                'build a city-builder game in a browser tab. i still build',
                "cities, only now they're component trees, design systems,",
                'and the occasional actual product.',
                '',
                'three words my friends use: cheerful, flexible, loyal.',
                'one word i would add: obsessive (about easing curves).',
                '',
                "the work i'm proudest of is the work nobody notices —",
                'a 200ms response that should have been 1.2s,',
                'a form that fits in your head,',
                'a chart that reads on first glance.',
            ].join('\n'),
        },
        {
            type: 'file',
            name: 'contact.md',
            content: [
                '# contact',
                '',
                'web       afiqakm.dev',
                'email     hi@afiqakm.dev',
                'github    github.com/afiqakm',
                'read.cv   read.cv/afiqakm',
                'are.na    are.na/afiqakm',
                'rss       afiqakm.dev/rss.xml',
                '',
                'open to: lead frontend / staff roles at small product teams,',
                '         interesting freelance, late-stage thoughtful chats.',
                '',
                'closed to: web3, "ai-first" anything, recruiter dms with',
                '           "hi {{first_name}}" still in the template.',
            ].join('\n'),
        },
        {
            type: 'file',
            name: 'links.txt',
            content: [
                'afiqakm.dev',
                'github.com/afiqakm',
                'read.cv/afiqakm',
                'are.na/afiqakm',
                'afiqakm.dev/rss.xml',
            ].join('\n'),
        },
        {
            type: 'dir',
            name: 'work',
            children: [
                {
                    type: 'dir',
                    name: 'linea',
                    children: [
                        {
                            type: 'file',
                            name: 'readme.md',
                            content: [
                                '# linea — realtime collaborative design tool',
                                '',
                                'role     lead engineer',
                                'team     8 (3 eng, 4 design, 1 pm)',
                                'years    2024 — present',
                                'stack    typescript · react · custom webgl renderer · yjs',
                                '',
                                '## what',
                                'a multiplayer canvas for product designers. think',
                                "figma's ergonomics, but built for product teams that",
                                'live half in code.',
                                '',
                                '## the work',
                                '- wrote a custom webgl renderer because canvas2d',
                                '  was wheezing past 200 concurrent cursors.',
                                '- built the crdt layer (yjs) and the conflict-resolution',
                                '  ux on top — moves, group edits, ghost selections.',
                                '- shipped the first interaction model, then deleted',
                                '  half of it after watching real users.',
                                '',
                                '## numbers',
                                '- ~14k LOC TypeScript',
                                '- 60fps with 200+ concurrent cursors',
                                '- 3 ms median operation roundtrip',
                            ].join('\n'),
                        },
                        {
                            type: 'file',
                            name: 'stack.txt',
                            content: 'typescript · react · webgl · yjs · rust (worker) · postgres',
                        },
                    ],
                },
                {
                    type: 'dir',
                    name: 'halcyon',
                    children: [
                        {
                            type: 'file',
                            name: 'readme.md',
                            content: [
                                '# halcyon bank — kyc onboarding rebuild',
                                '',
                                'role     tech lead, frontend',
                                'years    2023 — 2024',
                                'stack    typescript · react · zod · server-driven ui',
                                '',
                                '## what',
                                'a regulated bank in southeast asia, doing identity',
                                'verification at scale. the old flow took 11 minutes',
                                'median; we needed it under 4.',
                                '',
                                '## the work',
                                '- redesigned the form engine to be server-driven',
                                '  (the bank rule-set changes weekly).',
                                '- twelve a/b experiments in five months.',
                                '- killed two whole steps by precomputing on backend.',
                                '- added a chunky undo system because users were',
                                '  terrified of taking the wrong photo.',
                                '',
                                '## numbers',
                                '- median KYC time: 11m → 3m',
                                '- D1 completion: 58% → 81%',
                                '- support volume: ~38% lower in three months',
                            ].join('\n'),
                        },
                    ],
                },
                {
                    type: 'dir',
                    name: 'field-notes',
                    children: [
                        {
                            type: 'file',
                            name: 'readme.md',
                            content: [
                                '# field-notes — observable node logger',
                                '',
                                'role     solo · open source',
                                'years    2024',
                                'stack    node · react · web components',
                                '',
                                '## what',
                                'a node logger that writes structured events and ships',
                                'with a built-in time-travel ui. instead of reading 10k',
                                'lines of json, you scrub through your request.',
                                '',
                                '## numbers',
                                '- 2.3k★ on github',
                                '- 30k weekly downloads',
                                '- featured on bytes, react status, hackernews front page',
                            ].join('\n'),
                        },
                    ],
                },
                {
                    type: 'dir',
                    name: 'pacer',
                    children: [
                        {
                            type: 'file',
                            name: 'readme.md',
                            content: [
                                '# pacer — a running coach app',
                                '',
                                'role     fe + dsp',
                                'years    2023',
                                'stack    swift · react native · webaudio · shared rust core',
                                '',
                                '## what',
                                'a running app that listens for your footfall and',
                                'coaches your cadence in realtime. ios + web, with',
                                'a shared rust core for the audio dsp.',
                                '',
                                '## the work',
                                '- wrote the cadence-detection algorithm in pure',
                                '  webaudio (autocorrelation on a windowed buffer).',
                                '- ported it to rust for the ios app to keep parity.',
                                '- designed the haptic + audio coach so it works',
                                '  even when you have headphones in and music up.',
                            ].join('\n'),
                        },
                    ],
                },
                {
                    type: 'dir',
                    name: 'saga',
                    children: [
                        {
                            type: 'file',
                            name: 'readme.md',
                            content: [
                                '# saga — narrative-first headless cms',
                                '',
                                'role     co-founder · design + frontend',
                                'years    2021 — 2023',
                                '',
                                'a cms for novelists and longform writers. shut down',
                                "in 2023 — couldn't find a market we could serve well.",
                                'wrote the postmortem in writing/.',
                            ].join('\n'),
                        },
                    ],
                },
            ],
        },
        {
            type: 'dir',
            name: 'writing',
            children: [
                {
                    type: 'file',
                    name: '2026-05_friction.md',
                    content: [
                        '# the opposite of friction is not speed',
                        '',
                        'may 2026 · 4 min read',
                        '',
                        'we keep optimizing for "fast." but most of the things',
                        'i remember loving — a film, a record, a meal — were not',
                        'fast. they were calm. friction is a distraction from',
                        'a poorly-defined goal; speed is what you get when you',
                        'remove the friction. but the goal was never speed.',
                        '',
                        '...continued at afiqakm.dev/friction',
                    ].join('\n'),
                },
                {
                    type: 'file',
                    name: '2026-02_boring-tech.md',
                    content: [
                        '# on choosing boring technology, again',
                        '',
                        'feb 2026 · 6 min read',
                        '',
                        "a senior engineer's case for being delightfully",
                        'uninteresting. the technologies you pick determine',
                        'the conversations you can have. boring tech buys you',
                        'attention you can spend somewhere that matters.',
                        '',
                        '...continued at afiqakm.dev/boring-tech',
                    ].join('\n'),
                },
                {
                    type: 'file',
                    name: '2025-11_crdts.md',
                    content: [
                        '# crdts for people who hate crdts',
                        '',
                        'nov 2025 · 11 min read',
                        '',
                        'a practical, mostly-correct guide. with pictures.',
                        'covers: why your collaborative editor probably does',
                        'not need yjs, why mine did, and how to tell which',
                        'side of that line you are on.',
                    ].join('\n'),
                },
                {
                    type: 'file',
                    name: '2025-08_team-of-one.md',
                    content: [
                        '# a team of one',
                        '',
                        'aug 2025 · 3 min read',
                        '',
                        'how leading frontend at a five-person company taught',
                        'me to delete things. mostly: my own code.',
                    ].join('\n'),
                },
                {
                    type: 'file',
                    name: '2025-05_imperceptible.md',
                    content: [
                        '# imperceptible animation',
                        '',
                        'may 2025 · 8 min read',
                        '',
                        'a piece on micro-motion: the 80ms easing that makes a',
                        'list feel "alive" without ever looking animated.',
                    ].join('\n'),
                },
            ],
        },
        {
            type: 'dir',
            name: 'stack',
            children: [
                {
                    type: 'file',
                    name: 'daily.toml',
                    content: [
                        '# things i write every day',
                        'languages   = ["typescript"]',
                        'frameworks  = ["react", "node", "vite"]',
                        'styling     = ["tailwind", "css modules"]',
                        'data        = ["postgres", "zod"]',
                    ].join('\n'),
                },
                {
                    type: 'file',
                    name: 'often.toml',
                    content: [
                        '# things i pick up most weeks',
                        'graphics    = ["three.js", "glsl", "canvas2d"]',
                        'systems     = ["rust", "bun"]',
                        'state       = ["zustand", "yjs"]',
                        'testing     = ["playwright", "vitest"]',
                    ].join('\n'),
                },
                {
                    type: 'file',
                    name: 'sometimes.toml',
                    content: [
                        '# tools i pull out for the right job',
                        'native      = ["swift", "react native"]',
                        'backend     = ["go", "elixir"]',
                        'creative    = ["figma plugins", "webaudio"]',
                    ].join('\n'),
                },
                {
                    type: 'file',
                    name: 'curious.toml',
                    content: [
                        "# things i'm studying in 2026",
                        'effect_ts       = "structured concurrency in TS"',
                        'mojo            = "python-shaped, MLIR-backed"',
                        'wgpu            = "the shape of graphics post-webgpu"',
                        'local_first     = "sync that is also offline-first"',
                    ].join('\n'),
                },
            ],
        },
        {
            type: 'dir',
            name: 'now',
            children: [
                {
                    type: 'file',
                    name: 'now.md',
                    content: [
                        '# now — may 2026',
                        '',
                        '· leading frontend on an unannounced collaborative tool',
                        '· writing every other friday at afiqakm.dev',
                        '· reading: "the timeless way of building" (alexander)',
                        '· running 35km/week, slowly',
                        '· learning: rust async, slowly',
                        '· not learning: web3, ever',
                    ].join('\n'),
                },
            ],
        },
    ],
};
